### Portfolio3-Random Forest-Part2-Larger Dataset
#### Qiaoyu Wang

For the second part, I diverged by downloading a new, larger dataset (https://www.kaggle.com/datasets/teejmahal20/airline-passenger-satisfaction)  and fed it into the model to assess prediction accuracy, trying to find some insights into how the model behaves with more extensive data.

#### 0 Import

In [1]:
#Import libraries 
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
pd.set_option("display.max_rows",1000)
pd.set_option("display.max_columns",1000)
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

#### 1 Load in the dataset

In [2]:
df = pd.read_csv("data/air_satisfication.csv")
df = df.dropna()
df

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,1,5,3,5,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,3,1,3,1,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,2,5,5,5,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,5,2,2,2,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,3,4,5,5,3,3,4,4,3,3,3,0,0.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,103899,94171,Female,disloyal Customer,23,Business travel,Eco,192,2,1,2,3,2,2,2,2,3,1,4,2,3,2,3,0.0,neutral or dissatisfied
103900,103900,73097,Male,Loyal Customer,49,Business travel,Business,2347,4,4,4,4,2,4,5,5,5,5,5,5,5,4,0,0.0,satisfied
103901,103901,68825,Male,disloyal Customer,30,Business travel,Business,1995,1,1,1,3,4,1,5,4,3,2,4,5,5,4,7,14.0,neutral or dissatisfied
103902,103902,54173,Female,disloyal Customer,22,Business travel,Eco,1000,1,1,1,5,1,1,1,1,4,5,1,5,4,1,0,0.0,neutral or dissatisfied
103903,103903,62567,Male,Loyal Customer,27,Business travel,Business,1723,1,3,3,3,1,1,1,1,1,1,4,4,3,1,0,0.0,neutral or dissatisfied

In [3]:
encoded_y = LabelEncoder().fit_transform(df["satisfaction"])
print(encoded_y)
print(len(encoded_y), len(df["satisfaction"]))
print(np.unique(encoded_y))

[0 0 1 ... 0 0 0]
103594 103594
[0 1]

In [4]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [5]:
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])
df['Customer Type'] = LabelEncoder().fit_transform(df['Customer Type'])
df['Type of Travel'] = LabelEncoder().fit_transform(df['Type of Travel'])
df['Class'] = LabelEncoder().fit_transform(df['Class'])

#### 2 Train Random Forest model

In [8]:
def get_dataset(features):
    #Filter just features
    df_features = df[features].copy()
    X = df_features.values.copy()
    #Filter genres and add label column
    df_features.loc[df['satisfaction'] == "satisfied", "label"] = 0
    df_features.loc[df['satisfaction'] == "neutral or dissatisfied", "label"] = 1
    
    X = df_features.drop(columns=['label']).values  # Features matrix
    y = df_features['label'].values  # Target labels

    return X, y

def train(dataset, rf=True):
    X, y = dataset
    # Fit the model
    model = RandomForestClassifier(oob_score=True, random_state=42, n_estimators=200, n_jobs=-1)
    model.fit(X, y)
    print("OOB accuracy", model.oob_score_)
    return model

In [9]:
# features = ["Flight Distance", "Food and drink"]
# train(get_dataset(features))
features = ['Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes']
train(get_dataset(features))

OOB accuracy 0.9626040118153562

RandomForestClassifier(n_estimators=200, n_jobs=-1, oob_score=True,
                       random_state=42)